export type MenuGalleryItem = {
  src: string;
  category: "starters" | "soups" | "meat" | "seafood" | "vegetables" | "rice" | "desserts";
  pt: string;
  en: string;
};

const menuImage = (file: string) => `/images/menu/${file}`;
const newMenuImage = (file: string) => `/images/menu-items-new/${file}`;

export const MENU_GALLERY: MenuGalleryItem[] = [
  { src: menuImage("DSC05992.webp"), category: "starters", pt: "Edamame", en: "Edamame" },
  { src: menuImage("DSC06002.webp"), category: "starters", pt: "Har gow", en: "Steamed shrimp dumpling" },
  { src: menuImage("DSC06005.webp"), category: "starters", pt: "Siu mai", en: "Steamed shrimp and pork dumpling" },
  { src: menuImage("DSC06008.webp"), category: "starters", pt: "Xiao long bao", en: "Xiao long bao" },
  { src: menuImage("DSC06013.webp"), category: "starters", pt: "Gambas fritas", en: "Fried prawns" },
  { src: menuImage("DSC06028.webp"), category: "starters", pt: "Rolinhos de primavera", en: "Mini spring rolls" },
  { src: menuImage("DSC06040.webp"), category: "starters", pt: "Rolo de camarão com manga", en: "Rolls of shrimp and mango" },
  { src: menuImage("DSC06048.webp"), category: "starters", pt: "Ravioli de pato aberto", en: "Open duck ravioli" },
  { src: menuImage("DSC06064.webp"), category: "starters", pt: "Nuggets de frango", en: "Chicken nuggets" },
  { src: menuImage("DSC06065.webp"), category: "starters", pt: "Carne crocante frita", en: "Crispy fried chicken" },
  { src: menuImage("DSC06094.webp"), category: "starters", pt: "Salada de algas", en: "Seaweed salad" },
  { src: menuImage("DSC06100.webp"), category: "starters", pt: "Pãozinho doce frito", en: "Fried bread with sweet milk sauce" },
  { src: menuImage("DSC06293.webp"), category: "meat", pt: "Carne de vaca fria com molho leve", en: "Cold beef with mild sauce" },
  { src: menuImage("22b8eaa06a6e57c5be9c475aa182afab.webp"), category: "starters", pt: "Salada", en: "Salad" },
  { src: menuImage("DSC06434.webp"), category: "starters", pt: "Salada com presunto espanhol", en: "Salad with Spanish ham" },
  { src: menuImage("Dragon Kitchen Maio 2025 (21).webp"), category: "starters", pt: "Xiao long bao de carne de porco", en: "Pork xiao long bao" },

  { src: menuImage("DSC06273.webp"), category: "soups", pt: "Sopa de macarrão de arroz com delícias do mar", en: "Crab and vermicelli soup" },
  { src: menuImage("DSC06279.webp"), category: "soups", pt: "Sopa ácida e picante com vaca e camarão", en: "Spicy sour soup with beef and shrimp" },
  { src: menuImage("DSC06284.webp"), category: "soups", pt: "Sopa de frutos do mar", en: "Seafood soup" },
  { src: menuImage("DSC06597.webp"), category: "soups", pt: "Sopa de wantan", en: "Wantan soup" },

  { src: menuImage("DSC00156 copiar.webp"), category: "meat", pt: "Lombo Black Angus 300 g", en: "300 g Black Angus sirloin" },
  { src: menuImage("DSC00160 copiar.webp"), category: "meat", pt: "Couve-flor salteada com porco", en: "Stir-fried cauliflower with pork" },
  { src: menuImage("DSC00171 copiar.webp"), category: "meat", pt: "Couve salteada com porco", en: "Stir-fried cabbage with pork" },
  { src: menuImage("DSC02543 copiar.webp"), category: "meat", pt: "Frango picante em cubos", en: "Spicy diced chicken" },
  { src: menuImage("DSC06216.webp"), category: "meat", pt: "Tiras de porco com molho à Pequim", en: "Pork strips with Peking sauce" },
  { src: menuImage("DSC06224.webp"), category: "meat", pt: "Pato à Pequim", en: "Peking duck" },
  { src: menuImage("DSC06254.webp"), category: "meat", pt: "Carne de porco empanada agridoce", en: "Sweet and sour breaded pork" },
  { src: menuImage("DSC06262.webp"), category: "meat", pt: "Camarão com alho", en: "Garlic prawns" },
  { src: menuImage("DSC06365.webp"), category: "meat", pt: "Frango agridoce em cubos", en: "Sweet and sour diced chicken" },
  { src: menuImage("DSC06601.webp"), category: "meat", pt: "Costela de cordeiro com batatas", en: "Lamb ribs with potatoes" },
  { src: menuImage("DSC06609.webp"), category: "starters", pt: "Panada de frango", en: "Breaded chicken" },

  { src: menuImage("DSC06075.webp"), category: "seafood", pt: "Amêijoas à portuguesa", en: "Portuguese-style clams" },
  { src: menuImage("DSC06081.webp"), category: "seafood", pt: "Vieira com alho e massa de arroz", en: "Scallop with garlic and rice noodles" },
  { src: menuImage("DSC06090.webp"), category: "starters", pt: "Camarões empanados em fios de batata", en: "Fried shrimps with potato threads" },
  { src: menuImage("DSC06109.webp"), category: "starters", pt: "Tofu crocante", en: "Crispy tofu" },
  { src: menuImage("DSC06162.webp"), category: "seafood", pt: "Camarão com sal e pimenta", en: "Salt and pepper prawns" },
  { src: menuImage("4.webp"), category: "seafood", pt: "Lagosta com gengibre e cebolinha", en: "Lobster with ginger and spring onion" },
  { src: menuImage("DSC06237.webp"), category: "seafood", pt: "Peixe estilo esquilo", en: "Squirrel-style fish" },
  { src: menuImage("DSC06331.webp"), category: "seafood", pt: "Peixe ao vapor", en: "Steamed fish" },
  { src: menuImage("DSC06337.webp"), category: "seafood", pt: "Camarão com alho e massa de arroz", en: "Garlic prawns with rice noodles" },
  { src: menuImage("DSC06439.webp"), category: "seafood", pt: "Camarão recheado com molho de abalone", en: "Stuffed prawns with abalone sauce" },
  { src: menuImage("DSC06478.webp"), category: "seafood", pt: "Sapateira com gengibre e cebolinho", en: "Brown crab with ginger and spring onion" },
  { src: menuImage("Dragon Kitchen Maio 2025 (1).webp"), category: "seafood", pt: "Fatias de abalone com espargos salteados", en: "Sliced abalone with stir-fried asparagus" },

  { src: menuImage("DSC06120.webp"), category: "vegetables", pt: "Beringela Yu Xiang", en: "Yu Xiang aubergine" },
  { src: menuImage("DSC06167.webp"), category: "vegetables", pt: "Verdura conservada salteada", en: "Stir-fried preserved vegetables" },
  { src: menuImage("DSC06352.webp"), category: "vegetables", pt: "Tofu caseiro", en: "Homestyle tofu" },
  { src: menuImage("DSC06415.webp"), category: "vegetables", pt: "Batata em tiras com molho agridoce picante", en: "Potato strips with spicy sweet and sour sauce" },
  { src: menuImage("Dragon Kitchen Maio 2025 (5).webp"), category: "meat", pt: "Tofu mapo com vaca", en: "Mapo tofu with beef" },
  { src: menuImage("Dragon Kitchen Maio 2025 (11).webp"), category: "starters", pt: "Pepino com molho de soja", en: "Cucumber with soy sauce" },

  { src: menuImage("DSC06399.webp"), category: "rice", pt: "Arroz crocante com frango e vaca", en: "Crispy rice with chicken and beef" },
  { src: menuImage("DSC06409.webp"), category: "rice", pt: "Arroz crocante com frutos do mar", en: "Crispy rice with seafood" },
  { src: menuImage("DSC06450.webp"), category: "rice", pt: "Arroz frito com ovo", en: "Egg fried rice" },
  { src: menuImage("DSC06485.webp"), category: "rice", pt: "Massa de arroz com camarão", en: "Rice noodles with prawns" },
  { src: menuImage("DSC06556.webp"), category: "rice", pt: "Arroz frito tailandês com caril e ananás", en: "Thai fried rice with curry and pineapple" },
  { src: menuImage("DSC06564.webp"), category: "rice", pt: "Arroz frito com trufa preta e vaca", en: "Fried rice with black truffle and beef" },
  { src: menuImage("DSC06569.webp"), category: "rice", pt: "Massa de arroz com vaca", en: "Rice noodles with beef" },
  { src: menuImage("DSC06576.webp"), category: "rice", pt: "Massa de arroz com frango", en: "Rice noodles with chicken" },
  { src: menuImage("DSC06588.webp"), category: "rice", pt: "Massa salteada com frango", en: "Stir-fried noodles with chicken" },
  { src: menuImage("Dragon Kitchen Maio 2025 (16).webp"), category: "starters", pt: "Frango com arroz glutinoso", en: "Chicken with glutinous rice" },
  { src: menuImage("DSC05361 copiar.webp"), category: "desserts", pt: "Cheesecake de pistache", en: "Pistachio cheesecake" },
  { src: menuImage("DSC05371 copiar.webp"), category: "desserts", pt: "Mochi mirtilo", en: "Blueberry mochi" },
  { src: menuImage("DSC05377 copiar.webp"), category: "desserts", pt: "Mochi pistache", en: "Pistachio mochi" },
  { src: menuImage("DSC05380 copiar.webp"), category: "desserts", pt: "Mochi manga", en: "Mango mochi" },
  { src: menuImage("DSC06634.webp"), category: "desserts", pt: "Gelado frito", en: "Fried ice cream" },

  // New menu images from public/images/menu-items-new
  { src: newMenuImage("05 Sopa de vaca com espargos.webp"), category: "soups", pt: "Sopa de vaca com espargos", en: "Beef and asparagus soup" },
  { src: newMenuImage("06 Ensopado de pato.webp"), category: "meat", pt: "Ensopado de pato", en: "Duck stew" },
  { src: newMenuImage("100 massa de arroz salteado com legumes.webp"), category: "rice", pt: "Massa de arroz salteada com legumes", en: "Stir-fried rice noodles with vegetables" },
  { src: newMenuImage("110 sopa de massa udon com camarao.webp"), category: "rice", pt: "Sopa de massa udon com camarão", en: "Udon noodle soup with prawns" },
  { src: newMenuImage("12 Wantan Frito.webp"), category: "starters", pt: "Wantan frito", en: "Fried wontons" },
  { src: newMenuImage("14 amendoins cozidos.webp"), category: "starters", pt: "Amendoins cozidos", en: "Boiled peanuts" },
  { src: newMenuImage("200 mochi baunilha.webp"), category: "desserts", pt: "Mochi de baunilha", en: "Vanilla mochi" },
  { src: newMenuImage("208 bolas de abobora com recheio de coco.webp"), category: "desserts", pt: "Bolas de abóbora com recheio de coco", en: "Pumpkin balls with coconut filling" },
  { src: newMenuImage("209 ovo de manga com chocolate branco.webp"), category: "desserts", pt: "Ovo de manga com chocolate branco", en: "Mango egg with white chocolate" },
  { src: newMenuImage("210 pedra matcha de coco.webp"), category: "desserts", pt: "Pedra de matcha e coco", en: "Matcha and coconut stone" },
  { src: newMenuImage("211 docura oriental.webp"), category: "desserts", pt: "Doçura oriental", en: "Oriental delight" },
  { src: newMenuImage("22 ravioli de porco.webp"), category: "starters", pt: "Ravioli de porco", en: "Pork dumplings" },
  { src: newMenuImage("24 frango fumado.webp"), category: "starters", pt: "Frango fumado", en: "Smoked chicken" },
  { src: newMenuImage("25 bamboo.webp"), category: "starters", pt: "Rebentos de bambu", en: "Bamboo shoots" },
  { src: newMenuImage("28 camarao algarve.webp"), category: "seafood", pt: "Camarão à Algarve", en: "Algarve-style prawns" },
  { src: newMenuImage("32 paozinho coelho com ovo doce.webp"), category: "starters", pt: "Pãozinho coelho com creme de ovo doce", en: "Rabbit bun with sweet egg custard" },
  { src: newMenuImage("34 paozinhos de nozes.webp"), category: "starters", pt: "Pãezinhos de nozes", en: "Walnut buns" },
  { src: newMenuImage("37 frango frito com amendoa.webp"), category: "starters", pt: "Frango frito com amêndoa", en: "Fried chicken with almonds" },
  { src: newMenuImage("38 ostias de camarao.webp"), category: "starters", pt: "Hóstias de camarão", en: "Prawn crackers" },
  { src: newMenuImage("39 batatas fritas.webp"), category: "starters", pt: "Batatas fritas", en: "French fries" },
  { src: newMenuImage("40 galinha cozido a vapor com molho picante.webp"), category: "meat", pt: "Galinha cozida a vapor com molho picante", en: "Steamed chicken with spicy sauce" },
  { src: newMenuImage("42 tendao de bovinho marinado.webp"), category: "starters", pt: "Tendão de bovino marinado", en: "Marinated beef tendon" },
  { src: newMenuImage("43 massa de pato a pequim.webp"), category: "rice", pt: "Massa com pato à Pequim", en: "Noodles with Peking duck" },
  { src: newMenuImage("45 Peixe Cozido com Pimenta.webp"), category: "seafood", pt: "Peixe cozido com pimenta", en: "Poached fish with chilli" },
  { src: newMenuImage("52 porco agridoce.webp"), category: "meat", pt: "Porco agridoce", en: "Sweet and sour pork" },
  { src: newMenuImage("53 pato com laranja.webp"), category: "meat", pt: "Pato com laranja", en: "Duck with orange sauce" },
  { src: newMenuImage("58 Lula com sal e pimenta.webp"), category: "seafood", pt: "Lula com sal e pimenta", en: "Salt and pepper squid" },
  { src: newMenuImage("59 shop-suey de Camarao Misto.webp"), category: "seafood", pt: "Chop suey misto de camarão", en: "Mixed prawn chop suey" },
  { src: newMenuImage("60 chop-suey de Frango Misto.webp"), category: "meat", pt: "Chop suey misto de frango", en: "Mixed chicken chop suey" },
  { src: newMenuImage("65 cubos carne WAGYU com alho e pimenta preta.webp"), category: "meat", pt: "Cubos de carne Wagyu com alho e pimenta-preta", en: "Wagyu beef cubes with garlic and black pepper" },
  { src: newMenuImage("66 chop-suey de vaca misto.webp"), category: "meat", pt: "Chop suey misto de vaca", en: "Mixed beef chop suey" },
  { src: newMenuImage("67 mao xue wang.webp"), category: "meat", pt: "Mao Xue Wang", en: "Mao Xue Wang (spicy Sichuan stew)" },
  { src: newMenuImage("68 entremetada dupla.webp"), category: "meat", pt: "Entremeada duplamente salteada", en: "Twice-cooked pork belly" },
  { src: newMenuImage("70 camarao com massa de arroz cozido.webp"), category: "rice", pt: "Camarão com massa de arroz cozida", en: "Prawns with rice noodles" },
  { src: newMenuImage("73 frango kung pao.webp"), category: "meat", pt: "Frango Kung Pao", en: "Kung Pao chicken" },
  { src: newMenuImage("77 carne de vaca com molho de ostras.webp"), category: "meat", pt: "Carne de vaca com molho de ostras", en: "Beef with oyster sauce" },
  { src: newMenuImage("78 carne de vaca com bamboo e cogumelos.webp"), category: "meat", pt: "Carne de vaca com bambu e cogumelos", en: "Beef with bamboo shoots and mushrooms" },
  { src: newMenuImage("80 carne de porco com bamboo e cogumelos.webp"), category: "meat", pt: "Carne de porco com bambu e cogumelos", en: "Pork with bamboo shoots and mushrooms" },
  { src: newMenuImage("83 frango ao  caril.webp"), category: "meat", pt: "Frango com caril", en: "Chicken curry" },
  { src: newMenuImage("84 carne de vaca ao caril.webp"), category: "meat", pt: "Carne de vaca com caril", en: "Beef curry" },
  { src: newMenuImage("85 cabrito cozido.webp"), category: "meat", pt: "Cabrito cozido", en: "Braised goat" },
  { src: newMenuImage("86 Tofu Japones na chapa.webp"), category: "vegetables", pt: "Tofu japonês na chapa", en: "Sizzling Japanese tofu" },
  { src: newMenuImage("87 Espargos salteado.webp"), category: "vegetables", pt: "Espargos salteados", en: "Stir-fried asparagus" },
  { src: newMenuImage("94 cogumelos eryngii salteados.webp"), category: "vegetables", pt: "Cogumelos eryngii salteados", en: "Stir-fried king oyster mushrooms" },
  { src: newMenuImage("95 Chu chu.webp"), category: "vegetables", pt: "Chuchu", en: "Chayote" },
  { src: newMenuImage("96massa salteado  com legumes.webp"), category: "rice", pt: "Massa salteada com legumes", en: "Stir-fried noodles with vegetables" },
  { src: newMenuImage("Bolinhas de camarao com molho de salada e mostrada.webp"), category: "seafood", pt: "Bolinhas de camarão com molho de salada e mostarda", en: "Prawn balls with salad dressing and mustard" },
  { src: newMenuImage("Panado de camarao com milho.webp"), category: "seafood", pt: "Camarão panado com milho", en: "Breaded prawns with sweetcorn" },
  { src: newMenuImage("camarao sem casca com alho e massa de arroz.webp"), category: "seafood", pt: "Camarão sem casca com alho e massa de arroz", en: "Peeled prawns with garlic and rice noodles" },
  { src: newMenuImage("camarao tigre.webp"), category: "seafood", pt: "Camarão-tigre", en: "Tiger prawns" },
  { src: newMenuImage("entremeada duplo salteada.webp"), category: "meat", pt: "Entremeada duplamente salteada", en: "Twice-cooked pork belly" },
  { src: newMenuImage("fatias de abalone com oleo de cebolinha.webp"), category: "seafood", pt: "Fatias de abalone com óleo de cebolinha", en: "Sliced abalone with spring onion oil" },
  { src: newMenuImage("frango com bamboo e cugumelos.webp"), category: "meat", pt: "Frango com bambu e cogumelos", en: "Chicken with bamboo shoots and mushrooms" },
  { src: newMenuImage("golden sopa acido picante com peixe.webp"), category: "seafood", pt: "Sopa dourada ácida e picante com peixe", en: "Golden hot and sour fish soup" },
  { src: newMenuImage("vaca salteada com tiras de rabanete.webp"), category: "meat", pt: "Vaca salteada com tiras de rabanete", en: "Stir-fried beef with shredded radish" },

  // Menu images added on 2026-10-03
  { src: newMenuImage("98 Massa salteado com Carne de Vaca (1).webp"), category: "rice", pt: "Massa salteada com carne de vaca", en: "Stir-fried noodles with beef" },
  { src: newMenuImage("Batatas fatiadas na panela seca.webp"), category: "vegetables", pt: "Batatas fatiadas na panela seca", en: "Dry-pot sliced potatoes" },
  { src: newMenuImage("Bolinhas de camarao com molho de salada e mostrada (1).webp"), category: "seafood", pt: "Bolinhas de camarão com molho de salada e mostarda", en: "Prawn balls with salad dressing and mustard" },
  { src: newMenuImage("Camarao agridoce.webp"), category: "seafood", pt: "Camarão agridoce", en: "Sweet and sour prawns" },
  { src: newMenuImage("Cheesecake matcha.webp"), category: "desserts", pt: "Cheesecake de matcha", en: "Matcha cheesecake" },
  { src: newMenuImage("Golden sopa acido picante com vaca.webp"), category: "soups", pt: "Sopa dourada ácida e picante com vaca", en: "Golden hot and sour beef soup" },
  { src: newMenuImage("Inhame salteado.webp"), category: "vegetables", pt: "Inhame salteado", en: "Stir-fried Chinese yam" },
  { src: newMenuImage("Lula salteada com legumes em comserva.webp"), category: "seafood", pt: "Lula salteada com legumes em conserva", en: "Stir-fried squid with preserved vegetables" },
  { src: newMenuImage("Mochi morango.webp"), category: "desserts", pt: "Mochi de morango", en: "Strawberry mochi" },
  { src: newMenuImage("Tofu na chapa com vaca.webp"), category: "meat", pt: "Tofu na chapa com vaca", en: "Sizzling tofu with beef" },
  { src: newMenuImage("camarao com creme e cogumelos.webp"), category: "seafood", pt: "Camarão com creme e cogumelos", en: "Prawns with cream and mushrooms" },
  { src: newMenuImage("frango na chapa.webp"), category: "meat", pt: "Frango na chapa", en: "Sizzling chicken" },
  { src: newMenuImage("gambas na chapa.webp"), category: "seafood", pt: "Gambas na chapa", en: "Sizzling prawns" },
  { src: newMenuImage("gelado baunilha.webp"), category: "desserts", pt: "Gelado de baunilha", en: "Vanilla ice cream" },
  { src: newMenuImage("massa de arroz em tiras largas salteada com camarao.webp"), category: "rice", pt: "Massa de arroz larga salteada com camarão", en: "Stir-fried wide rice noodles with prawns" },
  { src: newMenuImage("massa de arroz em tiras largas salteada com frango.webp"), category: "rice", pt: "Massa de arroz larga salteada com frango", en: "Stir-fried wide rice noodles with chicken" },
  { src: newMenuImage("massa de arroz em tiras largas salteada com legumes.webp"), category: "rice", pt: "Massa de arroz larga salteada com legumes", en: "Stir-fried wide rice noodles with vegetables" },
  { src: newMenuImage("massa de arroz em tiras largas salteada com vaca.webp"), category: "rice", pt: "Massa de arroz larga salteada com vaca", en: "Stir-fried wide rice noodles with beef" },
  { src: newMenuImage("mochi cheesecake.webp"), category: "desserts", pt: "Mochi de cheesecake", en: "Cheesecake mochi" },
  { src: newMenuImage("mochi chocolate.webp"), category: "desserts", pt: "Mochi de chocolate", en: "Chocolate mochi" },
  { src: newMenuImage("vaca na chapa.webp"), category: "meat", pt: "Vaca na chapa", en: "Sizzling beef" },
  { src: newMenuImage("vaca salteada com tiras de rabanete (1).webp"), category: "meat", pt: "Vaca salteada com tiras de rabanete", en: "Stir-fried beef with shredded radish" },
];
